name: develop build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env: 
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
  VCPKG_HOME: "${{ github.workspace }}/vcpkg"
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Export GitHub Actions cache environment variables
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
    - uses: lukka/get-cmake@latest
    - uses: actions/checkout@v4
      with:
        repository: "microsoft/vcpkg"
        ref: "acd5bba5aac8b6573b5f6f463dc0341ac0ee6fa4"

    - uses: actions/checkout@v4

    - name: Run workflow
      run: cmake --workflow ci
