name: develop build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env: 
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
  
jobs:
  build_matrix:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      - uses: lukka/get-cmake@latest
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: "microsoft/vcpkg"
          ref: "acd5bba5aac8b6573b5f6f463dc0341ac0ee6fa4"
          path: vcpkg
  
      - name: Install system dependencies
        run: sudo apt install libltdl-dev libx11-dev libxft-dev libxext-dev

      - name: Install system dependencies for ubuntu-22.04
        if: matrix.os == 'ubuntu-22.04'
        run:
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt-get update -y
          sudo apt-get install gcc-13 g++-13

  
      - name: Run workflow
        run: cmake --workflow ci
  
      - uses: actions/upload-artifact@v4
        with:
          name: "journal-viewer-${{ matrix.os }}"
          path: "build/journal-viewer-*.deb"
