name: 'Release'
on:
  push:
    tags:
      - '*'

jobs:
  build-project:
    uses: mathisloge/journal-viewer/.github/workflows/develop-build.yml@main

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build-project
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Download all build arifacts
        uses: actions/download-artifact@v4
        with:
            path: artifacts
            merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{steps.github_release.outputs.changelog}}
          files: artifacts/*
